language:
   - python

python:
   - 2.6
   - 2.7
   - 3.2
   - 3.3
   - 3.4
   - 3.5

addons:
  apt:
    packages:
    - python-vtk
    - python-pip
      #    - python-qt4
      #    - python-qt4-gl
      #    - python-imaging

  #cache:
  #   directories:
  #      - $HOME/.cache
  #      - $HOME/.ccache

before_install:
   #- ccache -s
   #- export PATH=/usr/lib/ccache:${PATH}
   - pip install --upgrade pip
    #  - export ETS_TOOLKIT=qt4
    #  - export DISPLAY=:99.0
    #  - export VTKDATA=/home/travis/VTKData
    #  - git clone --depth=1 --branch=master git://vtk.org/VTKData.git /home/travis/VTKData
    #  - sh -e /etc/init.d/xvfb start

install:
   - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]];
     then pip install pytest-cov python-coveralls;
     else pip install pytest;
     fi
     #- pip install mayavi
     #- pip install pep8

script:
   #- pep8 ./tests/run_tests.py
   - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]];
     then py.test -vv ./tests/run_tests.py --cov ./src;
     else py.test -vv ./tests/run_tests.py;
     fi

after_success:
   - if [[ $TRAVIS_PYTHON_VERSION == 2.6 ]];
     then coveralls;
     fi

notifications:
   email: false
